[tool.poetry]
name = "esphome-philips-ep2231"
version = "0.1.0"
description = ""
authors = ["Thies Gerken <thies@thiesgerken.de>"]
readme = "README.md"
packages = [{include = "esphome_philips_ep2231"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
esphome = ">=2026.8.0"

[tool.poetry.group.dev.dependencies]
ruff = ">=0.16"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
